      - name: HTMLProofer
        uses: chabad360/htmlproofer@v2
        with:
          directory: "./html"
          # The directory to scan
          arguments: --allow-missing-href
          # The arguments to pass to HTMLProofer
